;;===============================
;;Name: Antonio Calabrese
;;===============================

.orig x3000

		AND R0, R0, 0	;CLEAR THE FIRST REGISTER, THIS IS OUR SUM
		AND R1, R1, 0	;CLEAR SECOND REGISTER, THIS IS OUR NEGATIVE VARIABLE
		LD R2, V 		;LOAD UP V
		LD R3, U 		;LOAD U AND SET THE CONDITION CODE FOR NEXT PART

		BRZP LOOP		;IF IT IS LESS THAN 0 CONTINUE OTHERWISE SKIP THE STEP
		ADD R1, R1, 1 	;SET THE NEGATIVE VALUE TO 1
		NOT R3, R3 		;START BY FLIPPING THE BITS THEN ADD 1 TO MAKE IT NEGATIVE
		ADD R3, R3, 1	

LOOP	ADD R0, R0, R2	;INCREMENT THE SUM BY V
		ADD R3, R3, -1	;DECREMENT U
		BRP LOOP		;WHILE U IS POSITIVE DO THE LOOP

		ADD R1, R1, 0	;SET THE CONDITION CODE SO WE CAN TEST IF NEGATIVE
		BRZ SKIP		;IF THE NUMBER IS NOT NEGATIVE WE DON'T NEED TO NEGATE THE SUM
		NOT R0, R0		;NEGATING THE SUM BY FLIPPING THE BITS THEN ADDING ONE
		ADD R0, R0, 1
SKIP	ST R0, ANSWER	;RETURN THE ANSWER BACK TO THE CORRECT ADDRESS
		
		HALT		

U       .fill -3
V       .fill 4
ANSWER  .fill 0
.end

